# Generated by Django 4.2 on 2023-04-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_app_admin',
        ),
    ]
